config/routes.rb
Rails.application.routes.draw do
  
  get 'replies/index'

  get 'comments/index'

  get 'password_resets/new'
  get "log_in" => "sessions#new", :as => "log_in"
  post "log_in_user" => "sessions#create", :as => "log_in_user"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "users/index" => "users#index"
  get "articles/advertisment" => "articles#advertisment"
  post "sign_up_user" => "users#create", :as => "sign_up_user"
  get "comments/index"=> "comments#index"
  
  resources :users
  resources :sessions
  resources :articles
  resources :password_resets
  resources :comments

  root 'demo#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
		validates :name, presence: true

	validates :item, presence: true
		validates :amount, presence: true

     def self.search(search)
 		if search
    		self.where("name LIKE ? ", "%#{search}%")
    	else
    		self.all
  		end
	end
               
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	 belongs_to :replies

end

app/models/replies.rb
class Replies < ActiveRecord::Base
	belongs_to :comments

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	before_save :encrypt_password
  is_impressionable
  validates_presence_of :email
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_presence_of :phonenumber
  validates_presence_of :city
  validates_presence_of :state
before_create { generate_token(:auth_token) }


  def send_password_reset
  generate_token(:password_reset_token)
  self.password_reset_sent_at = Time.zone.now
  save!
  UserMailer.password_reset(self).deliver
end

def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
def impressionist_count
    impressions.size
  end
  # def unique_impression_count
  #   impressions.group(:ip_address).size #UNTESTED: might not be correct syntax
  # end

def self.authenticate(email, password)
  user = find_by_email(email)
  if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
    user
  else
    nil
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
helper_method :current_user
 private

 private
  def current_user
    @current_user ||= User.find_by_auth_token( cookies[:auth_token]) if cookies[:auth_token]
  end

def authenticate_user!
    unless current_user
      flash[:notice] = "Please Login And Continue!"
      redirect_to root_url
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :authenticate_user!

  def index

        @articles = Article.search(params[:search]).order("name").page(params[:page]).per(8)

   
end
	def new
    @article = Article.new
  end
  def show
  @article = Article.find(params[:id])
end
 
  def create
  @article = Article.new(article_params)
 
  if @article.save
    redirect_to articles_path, :notice => "successfully created!"
  else
    render 'new'
  end
end
def edit
  @article = Article.find(params[:id])
end
def update
  @article = Article.find(params[:id])
 
  if @article.update(article_params)
    redirect_to articles_path, :notice => "successfully Updated!"
  else
    render 'edit'
  end
end
def destroy
  @article = Article.find(params[:id])
  @article.destroy
 
  redirect_to articles_path, :notice => "successfully Deleted!"
end

def article_demo
  end
 
private
  def article_params
    params.require(:article).permit(:name, :item, :amount)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  	def index
@comments=Comment.new
@replies=Replies.new
end

  def create
  @comment =Comment.new(params[:commenter])
 

  if @comment.save
    redirect_to comments_path
  else
    render 'comments/index'
  end
end
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def index
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  respond_to :html, :js
  def new
  end
  def create
  user = User.find_by_email(params[:email])
  user.send_password_reset if user
  redirect_to root_url, :notice => "Email sent with password reset instructions."
end
def edit
  @user = User.find_by_password_reset_token!(params[:id])
end
def update
  @user = User.find_by_password_reset_token!(params[:id])
  if @user.password_reset_sent_at < 2.hours.ago
    redirect_to new_password_reset_path, :alert => "Password &crarr; 
      reset has expired."
  elsif @user.update_attributes(user_params)
    redirect_to root_url, :notice => "Password has been reset."
  else
    render :edit
  end
end
private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    respond_to :html, :js
  def new
    respond_to do |format|
    format.js { render 'new'}
  end
  end
  def index
    
  end
  
   def create
    user = User.find_by_email(params[:email])
    
  if user && User.authenticate(params[:email],params[:password])
     session[:user_id] = user.id
    if params[:remember_me]
      cookies.permanent[:auth_token] = user.auth_token
    else
      cookies[:auth_token] = user.auth_token  
    end
      redirect_to articles_advertisment_path, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

def destroy
 cookies.delete(:auth_token)
  redirect_to root_url, :notice => "Logged out successfully!"
end
# private
    # def sessions_params
    #   params.require(:user).permit(:email, :password)
    # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :js

 impressionist :unique => [:session_hash]
  def new
    @user = User.new
  end
  
  # def show
   
  #   @user = User.find(params[:id])
  #   impressionist(@user)
  #  end

   def index

     @user = current_user
     impressionist(@user)

   end
   


  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to articles_path, :notice => "Signed up!"
    else
      render "new"
    end
  end
  # def after_create(user)
  #   Counter.find_by_name("user_count").increment
  # end
  
  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :phonenumber, :city, :state)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/advertisment.html.erb
    <ul class="nav nav-tabs" id="myTab">
    <li class="active"><a href="#">Advertisment</a></li>
    <li><a href="http://localhost:3000/articles">Inventory</a></li>
    <li><a href="http://localhost:3000/users/index">Statics</a></li>
    </ul>
    <div class="tab-content">
    <div class="tab-pane active" id="Advertisment"></div>
    <div class="tab-pane" id="Inventory"></div>
    <div class="tab-pane" id="Statics"></div>
    
    </div>
    <script>
    $(function () {
   
    $('#myTab li:eq(1) a').tab('show');
    $('#myTab li:last a').tab('show');
    })
    </script>
<%= image_tag("carti.jpg",:width => 700,:height => 300)%><br/>

app/views/articles/edit.html.erb
  <%= form_for :article, url: article_path(@article), method: :patch do |f| %>
<% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this list from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <div class="form-group">
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
  </div>
 
  <div class="form-group">
    <%= f.label :Item %><br>
    <%= f.text_area :item %>
  </div>
<div class="form-group">
  <%= f.label :Amount %><br>
    <%= f.text_field :amount %>
  </div>

  <div class="form-group">
    <%= f.submit 'update', :class => "btn btn-warning" %>
    <%= link_to 'All Orders', articles_path, :class => "btn btn-warning" %>
  </div>
  <% end %>

 

app/views/articles/index.html.erb
<div class="row">

    <% @articles.each do |article| %>

    
    <div class="col-sm-3">
      
      <div class="well well-sm">
        

        <h4>Name: <%= article.name %></h4>
        <h5>Item: <%= article.item %></h5>
        <h6>Price: <%= article.amount %></h6>
        <hr>
        <div class="btn-group">
        <%= link_to 'Edit', edit_article_path(article), :class => "btn btn-info"%> 
        <%= link_to 'Destroy', article_path(article), :class => "btn btn-info",
        method: :delete, data: { confirm: ' Are you sure?' } %> 
        <%= link_to 'Show', article_path(article) , :class => "btn btn-info" %>
      </div>
      </div>



    </div>
    <% end %>
  </div>

  <div id="but"><%= link_to 'Add New Orders', new_article_path, :class => "btn btn-warning" %></div>
<div class="nav nav-pills pull-right"><%= paginate @articles %></div>
</div>

app/views/articles/new.html.erb
<h4>Add new Details</h4>
  <%= form_for :article, url: articles_path,:html => { :id => "new_order"} do |f| %>
  
    <div class="form-group">
      <%= f.label :Name %><br>
      <%= f.text_field :name %>
    </div>

    <div class="form-group">
      <%= f.label :Item %><br>
      <%= f.text_area :item %>
    </div>
    <div class="form-group">
      <%= f.label :Price %><br>
      <%= f.text_field :amount %>
    </div>

    <div class="form-group">
      <%= f.submit 'save' ,:class => "btn btn-warning" %>
       <%= link_to 'All Orders', articles_path, :class => "btn btn-warning"  %>
    </div>
    <% end %>
   

  

app/views/articles/show.html.erb
 
 	<%= image_tag("blink.gif",:width => 937,:height => 250,:class=>"img-rounded")%>
 	<p><strong>Jabong.com</strong> is an Indian fashion and lifestyle e-commerce portal. It retails apparel, footwear, accessories, beauty products, fragrances, home accessories and other fashion and lifestyle products.[2][3] The company is headquartered in Gurgaon, NCR.[4]</p>
 	<p>Name is
 		<%= @article.name %>
 	</p>
 	
 	<p>Order a item
 		<%= @article.item %>
 	</p>

 	<p>Cost for the item is 
 		<%= @article.amount %>
 	</p>
 	<%= link_to 'Add New Order', new_article_path, :class => "btn btn-warning" %>

 	<%= link_to 'All Orders', articles_path, :class => "btn btn-warning"  %>

app/views/comments/index.html.erb
<% Comment.all.each do |acomment| %>
<%= acomment.commenter %></br>

<% acomment.replies.each do |b| %>
<%= b.reply %><br/>
<% end %>

<%= form_for :replies do |rep|%>
<%= rep.text_field :reply %>
<%= rep.submit "Reply" %></br>
<% end %>
<% end %>

<%= form_for :comments, comments_path do |c|%>
<%= c.text_field :commenter %>
<%= c.submit "Add comment" %></br>
<% end %>

app/views/demo/index.html.erb
<%= image_tag("jabong logo.jpg",:width => 940,:height => 200)%><br/>
<%= image_tag("kids.jpg",:width => 940,:height => 500)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Details</title>
	<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %> 
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %> 
	<%= csrf_meta_tags %> 
	<script src="http://code.highcharts.com/highcharts.js"></script>


</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top headercolor"> JABONG.COM
		
		<% if current_user %>
		<%= link_to "Sign out", log_out_path,:class => "btn btn-sm btn-default pull-right "%>
		<%  elsif (controller_name == "sessions") && (action_name == "new") %>
		<%= link_to 'Sign Up',  sign_up_path, remote: true, :class => "btn btn-sm btn-default pull-right"   %>
		<%  elsif (controller_name == "users") && (action_name == ("new")) %>
		<%= link_to 'Sign In', log_in_path, remote: true,:class => "btn btn-sm btn-default pull-right"   %>  
		<% else %>
		<%= link_to 'Sign Up',  sign_up_path, remote: true, :class => "btn btn-sm btn-default pull-right"   %>   
		<%= link_to 'Sign In', log_in_path,remote: true, :class => "btn btn-sm btn-default pull-right"   %>  
		<% end %>
		<div class="nav nav-pills pull-left"><%= link_to "Home", root_path %></div>
		<div class="nav nav-pills pull-right"><%= form_tag articles_path,:method=>'get' do %>
        <%= text_field_tag :search %>
        <%= submit_tag "Search"%>
        <% end %>
	   </div>
	   </div>



	<div class="container">

		<div class="content">
		<div id="product-modal" class="modal"></div>
 
	<% flash.each do |name, msg| %>
	<div id="mess" class="bg-info"><button class="close" aria-hidden="true" data-dismiss="modal" type="button">×</button>
	<%= content_tag :div, msg, :id => "flash#{name}" %>
	<% end %>
	</div>
             
			<%= yield %>


			<div class="footer navbar-fixed-bottom footercolor" >
				<a href="#">@company 2014</a><br>

			</div>
		</div>
	</div>

</body>
</html>

app/views/password_resets/_new.html.erb
<div class="modal-header"><button class="close" aria-hidden="true" data-dismiss="modal" type="button">×</button>
<h3>Reset Password</h3></div>
<div class="modal-body">
<%= form_tag password_resets_path, :method => :post  do %>
  <div class="form-gruop">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div>
 

  <%= submit_tag "Reset Password" ,:class => "btn btn-info" %>
<% end %>
 </div>

app/views/password_resets/edit.html.erb
<h3>Reset Password</h3>

<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Update Password",:class => "btn btn-info" %></div>
<% end %>

app/views/password_resets/new.js.erb
$("#product-modal").html("<%= escape_javascript (render 'new') %>");
$("#product-modal").modal("show");

app/views/replies/index.html.erb
<h1>Replies#index</h1>
<p>Find me in app/views/replies/index.html.erb</p>

app/views/users/_new.html.erb
<div class="modal-header">
<button class="close" aria-hidden="true" data-dismiss="modal" type="button">×</button>
<h3>Sign Up</h3></div>
<div class="modal-body">
  <%=  form_for @user , url: sign_up_user_path(@user),  :authenticity_token => true, :html => { :id => "user_new"}  do |f| %>
  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="form-group">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="form-group">  
    <%= f.label :phonenumber %><br />
    <%= f.text_field :phonenumber %>
  </div>
  <div class="form-group">
    <%= f.label :city %><br />
    <%= f.text_field :city%>
  </p>
  <div class="form-group">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>

 
<%= f.submit 'Sign Up',:class => "btn btn-info" %>
    <%= link_to "Cancel", "#", :class => "btn btn-info", data: {dismiss: "modal"} %>

<% end %>
</div>

app/views/users/index.html.erb
  
     
         <div id="container" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div> 
          <div id="chart"><%=@user.impressionist_count %></div>
          	<div id="contain" style="min-width: 310px; max-width: 800px; height: 400px; margin: 0 auto"></div>

app/views/users/new.js.erb
$("#product-modal").html("<%= escape_javascript(render 'new') %>");
$("#product-modal").modal("show");
ValidateUser();